// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZe7n8SD-D0LqLPvCTkfzxtymXIDddqIk',
    appId: '1:320997602811:web:100e6142554f4aeda7475e',
    messagingSenderId: '320997602811',
    projectId: 'activity-app-e160f',
    authDomain: 'activity-app-e160f.firebaseapp.com',
    storageBucket: 'activity-app-e160f.appspot.com',
    measurementId: 'G-WYDGBMCFEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9EojaJOY8sBFZXAYRth45OaRpETEC5-0',
    appId: '1:320997602811:android:dd94e61cff79b1caa7475e',
    messagingSenderId: '320997602811',
    projectId: 'activity-app-e160f',
    storageBucket: 'activity-app-e160f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6dER-xLgXm1xD2pFp4yWO1_6LHJi55Lw',
    appId: '1:320997602811:ios:8ba39830cf8226ffa7475e',
    messagingSenderId: '320997602811',
    projectId: 'activity-app-e160f',
    storageBucket: 'activity-app-e160f.appspot.com',
    iosBundleId: 'com.example.project',
  );
}
